name: Release
on:
  push:
    tags: ["v[0-9]*"]
jobs:
  release:
    uses: kovagent/kit-ci/.github/workflows/release.yml@b776ff790842d9c41bb30cbd415c282889974aec
    with:
      crates: "indexkit indexkit-cli"
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
